# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Api

on:
    push:
        branches:
            - main
        paths:
            - Api/**
            - .github/workflows/api.yml
    workflow_run:
        workflows: ["terraform_apply"]
        branches: [main]
        types:
            - completed
    workflow_dispatch:

env:
    repo: domshyra

permissions:
    id-token: write
    contents: read

jobs:
    build:
        runs-on: windows-latest

        defaults:
            run:
                working-directory: Api

        steps:
            - uses: actions/checkout@v2

            - run: ls
            - name: Set up .NET Core
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: "9.0.x"
                  include-prerelease: true

            - name: Build with dotnet
              run: dotnet build --configuration Release

            - name: dotnet publish
              run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/Api

            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v4
              with:
                  name: .net-app
                  path: ${{env.DOTNET_ROOT}}/Api

    deploy:
        runs-on: windows-latest
        needs: build
        environment:
            name: "Production"
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: .net-app

            - name: Azure Login
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }} # save these as the federal credentials with no quotes
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            # https://learn.microsoft.com/en-us/azure/app-service/deploy-continuous-deployment?tabs=github%2Cgithubactions#configure-the-deployment-source
            # https://learn.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel%2Caspnetcore
            - name: Deploy to Azure Web App
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v2
              with:
                  app-name: "${{env.repo}}-api"
                  slot-name: "Production"
                  publish-profile: ${{ env.AZURE_APPSERVICE_PUBLISH_PROFILE_API }}
                  package: .
