# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Db

on:
    push:
        branches:
            - main
        paths:
            - Api/Data/**
            - .github/workflows/db.yml
    workflow_dispatch:

env:
    repo: domshyra
    kv: main-kv-domshyra

# https://learn.microsoft.com/en-us/azure/azure-sql/database/connect-github-actions-sql-db?view=azuresql&tabs=userlevel
jobs:
    build:
        runs-on: windows-latest

        defaults:
            run:
                working-directory: Api

        steps:
            - uses: actions/checkout@v2

            - uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}
            # - uses: Azure/get-keyvault-secrets@v1.0
            #   with:
            #     keyvault: ${{env.kv}}
            #     secrets: 'StorageAccountConnectionString'

            - run: ls
            - name: Set up .NET Core
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: "9.0.x"
                  include-prerelease: true

            - name: Build with dotnet
              run: dotnet build --configuration Release

            - name: App Settings Variable Substitution
              uses: microsoft/variable-substitution@v1
              with:
                  files: 'D:\a\${{env.repo}}\${{env.repo}}\Api\appsettings.json'
              env:
                  ConnectionStrings.DbConnectionString: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}

            - name: Add database with dotnet
              run: |
                  dotnet tool install --global dotnet-ef --version 9.0.3
                  dotnet tool restore
                  dotnet ef database update --connection '${{ secrets.AZURE_SQL_CONNECTION_STRING }}' -- --environment Production
