name: Web validation

on:
  pull_request:
    branches:
      - main
    paths:
      - Web/**
      - .github/workflows/web_validation.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: Web

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run coverage
          

      - name: JUnit Report Action
        # You may pin to the exact commit or the version.
        # uses: mikepenz/action-junit-report@62516aa379bff6370c95fd5894d5a27fb6619d9b
        uses: mikepenz/action-junit-report@v5.2.0
        with:
            # Specify the token to use to publish the check.
            token: ${{ github.token }} 
            # Xml report paths in glob format
            report_paths: Web/coverage/junit.xml
            # Prefix to add to test file paths from report files when annotating
            # Fail the build in case a test failure occurred.
            fail_on_failure: true
            # Fail the build if the test report file can not be parsed.
            fail_on_parse_error: true
            # Fail if no test are found.
            require_tests: true
            # Fail if no passed test are found.
            require_passed_tests: true
            # Additional text to summary output
            summary: true
            # Specify the name of a check to update
            job_name: ${{ github.job }}
            truncate_stack_traces: true

      # TODO! get the coverage report
      # - name: cobertura-report
      #   # You may pin to the exact commit or the version.
      #   # uses: 5monkeys/cobertura-action@ee5787cc56634acddedc51f21c7947985531e6eb
      #   uses: 5monkeys/cobertura-action@v14
      #   with:
      #         # The GITHUB_TOKEN for this repo
      #         # repo_token: ${{ github.token }}
      #         # Path to the cobertura file.
      #         path: Web/coverage/cobertura-coverage.xml
      #         # If files with 100% should be skipped from report.
      #         skip_covered: false
      #         # Minimum allowed coverage percentage as an integer.
      #         minimum_coverage: 0
      #         # Fail the action when the minimum coverage was not met.
      #         # fail_below_threshold: # optional
      #         # Show line rate as specific column.
      #         #show_line:  
      #         # Show branch rate as specific column.
      #         # show_branch: 
      #         # Show class names instead of file names.
      #         # show_class_names: 
      #         # Show line numbers of statements, per module, that was not executed.
      #         # show_missing: 
      #         # Crop missing line numbers strings that exceeds this length, provided as an integer.
      #         # show_missing_max_length: # optional, default is 
      #         # Link missing line numbers.
      #         # link_missing_lines: # optional
      #         # Source directory used for link_missing_lines.
      #         # link_missing_lines_source_dir: # optional, default is 
      #         # Only show coverage for changed files. (only if a PR is present)
      #         only_changed_files: true
      #         # Pull request number associated with the report. This property should be used when workflow trigger is different than pull_request.
      #         # pull_request_number: # optional, default is 
      #         # Use a unique name for the report and comment.
      #         report_name: coverage


