
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Web tsc validation

on:
  pull_request:
    branches:
      - main
    paths:
      - Web/**
      - .github/workflows/web.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: Web

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build
          

